#!/usr/bin/env python
# -*- coding: utf-8 -*-
# @Time    : 2019-5-10 15:16
# @Author  : zhdya@zhdya.cn
# @File    : TESTDDD.py

Asin = [{
					"key": "182.254.116.117",
					"doc_count": 1
				}, {
					"key": "51jiesan.com",
					"doc_count": 1
				}, {
					"key": "61.177.22.241",
					"doc_count": 1
				}, {
					"key": "admin.water.17usoft.com",
					"doc_count": 1
				}, {
					"key": "appnew.l",
					"doc_count": 1
				}, {
					"key": "cat.17usoft.com",
					"doc_count": 1
				}, {
					"key": "hotel.ly.com",
					"doc_count": 1
				}, {
					"key": "jco2oadmin.17usoft.com",
					"doc_count": 1
				}, {
					"key": "leo",
					"doc_count": 1
				}, {
					"key": "leonid",
					"doc_count": 1
				}, {
					"key": "leonidap",
					"doc_count": 1
				}, {
					"key": "leonidapi.1",
					"doc_count": 1
				}, {
					"key": "leonidapi.17uso",
					"doc_count": 1
				}, {
					"key": "leonidapi.17usoft.",
					"doc_count": 1
				}, {
					"key": "me.laidingba.com",
					"doc_count": 1
				}, {
					"key": "obt1.dttrip.cn",
					"doc_count": 1
				}, {
					"key": "passport.17u.net",
					"doc_count": 1
				}, {
					"key": "poseidon.ie.17usoft.com",
					"doc_count": 1
				}, {
					"key": "tckbms.tcly.cn",
					"doc_count": 1
				}, {
					"key": "tcw",
					"doc_count": 1
				}, {
					"key": "tcwlservice.",
					"doc_count": 1
				}, {
					"key": "tcwlservice.1",
					"doc_count": 1
				}, {
					"key": "tcwlservice.17usoft.c",
					"doc_count": 1
				}, {
					"key": "tcwlservice.17usoft.co",
					"doc_count": 1
				}, {
					"key": "vst",
					"doc_count": 1
				}, {
					"key": "vstlo",
					"doc_count": 1
				}, {
					"key": "vstlog.",
					"doc_count": 1
				}, {
					"key": "vstlog.17us",
					"doc_count": 1
				}, {
					"key": "water.17usoft.com",
					"doc_count": 1
				}, {
					"key": "wlouterapi.ly.com",
					"doc_count": 1
				}, {
					"key": "www.lvcang.com",
					"doc_count": 1
				}, {
					"key": "www.tianwang.17usoft.com",
					"doc_count": 1
				}, {
					"key": "xiangyula.com",
					"doc_count": 1
				}, {
					"key": "avg.ie.17usoft.com",
					"doc_count": 2
				}, {
					"key": "hapi.t.zhuketong.com",
					"doc_count": 2
				}, {
					"key": "join.ly.com",
					"doc_count": 2
				}, {
					"key": "leonidapi",
					"doc_count": 2
				}, {
					"key": "m.tongcheng.com",
					"doc_count": 2
				}, {
					"key": "m.xiangyula.com",
					"doc_count": 2
				}, {
					"key": "reservation.fly.17usoft.com",
					"doc_count": 2
				}, {
					"key": "scheduler.beetle.dss.17usoft.com",
					"doc_count": 2
				}, {
					"key": "tcm",
					"doc_count": 2
				}, {
					"key": "tuan1.ly.com",
					"doc_count": 2
				}, {
					"key": "wap.17u.com",
					"doc_count": 2
				}, {
					"key": "wechatapi.wanchengly.com",
					"doc_count": 2
				}, {
					"key": "airbus.fly.17usoft.com",
					"doc_count": 3
				}, {
					"key": "clearq.fly.17usoft.com",
					"doc_count": 3
				}, {
					"key": "dcopenapi.17usoft.com",
					"doc_count": 3
				}, {
					"key": "emotibot.17usoft.com",
					"doc_count": 3
				}, {
					"key": "tcmobil",
					"doc_count": 3
				}, {
					"key": "tcwlservic",
					"doc_count": 3
				}, {
					"key": "www.tchaomama.com",
					"doc_count": 3
				}, {
					"key": "aigobo.cn",
					"doc_count": 4
				}, {
					"key": "air.ly.com",
					"doc_count": 4
				}, {
					"key": "intlrebook.fly.17usoft.com",
					"doc_count": 4
				}, {
					"key": "m.51jiesan.com",
					"doc_count": 4
				}, {
					"key": "query.beetle.dss.17usoft.com",
					"doc_count": 4
				}, {
					"key": "tcmob",
					"doc_count": 4
				}, {
					"key": "tcmobile",
					"doc_count": 4
				}, {
					"key": "tcmobileapi.1",
					"doc_count": 4
				}, {
					"key": "pluto.tcent.cn",
					"doc_count": 6
				}, {
					"key": "plutusmng.ie.17usoft.com",
					"doc_count": 6
				}, {
					"key": "dcp.sre.17usoft.com",
					"doc_count": 7
				}, {
					"key": "shouji.ly.com",
					"doc_count": 7
				}, {
					"key": "tc",
					"doc_count": 7
				}, {
					"key": "tcmo",
					"doc_count": 7
				}, {
					"key": "tcmobileap",
					"doc_count": 7
				}, {
					"key": "zhxsrv.17u.cn",
					"doc_count": 7
				}, {
					"key": "manage.17usoft.com",
					"doc_count": 8
				}, {
					"key": "tcmobileapi.",
					"doc_count": 8
				}, {
					"key": "tcmobi",
					"doc_count": 9
				}, {
					"key": "tcmobilea",
					"doc_count": 9
				}, {
					"key": "log.1",
					"doc_count": 11
				}, {
					"key": "tcmobileapi",
					"doc_count": 11
				}, {
					"key": "tcmobileapi.17usof",
					"doc_count": 11
				}, {
					"key": "tcmobileapi.17usoft.co",
					"doc_count": 11
				}, {
					"key": "buscode.gstrain.17usoft.com",
					"doc_count": 12
				}, {
					"key": "riskmng.ie.17usoft.com",
					"doc_count": 12
				}, {
					"key": "tcmobileapi.17",
					"doc_count": 12
				}, {
					"key": "tcmobileapi.17us",
					"doc_count": 12
				}, {
					"key": "tcmobileapi.17usoft.",
					"doc_count": 12
				}, {
					"key": "agent.51jiesan.com",
					"doc_count": 13
				}, {
					"key": "ha.longrunning.bds.17usoft.com",
					"doc_count": 13
				}, {
					"key": "supplierorderapi.fly.17usoft.com",
					"doc_count": 13
				}, {
					"key": "zzyeb.ly.com",
					"doc_count": 13
				}, {
					"key": "nat1.ops.17usoft.com",
					"doc_count": 14
				}, {
					"key": "moa.t.17u.cn",
					"doc_count": 15
				}, {
					"key": "orderplacement.fly.17usoft.com",
					"doc_count": 16
				}, {
					"key": "tcmobileapi.17usoft",
					"doc_count": 16
				}, {
					"key": "train.17usoft.ne",
					"doc_count": 16
				}, {
					"key": "flightdrp.17u.cn",
					"doc_count": 17
				}, {
					"key": "ctripinnerapi.17usoft.com",
					"doc_count": 18
				}, {
					"key": "tcmobileapi.17u",
					"doc_count": 18
				}, {
					"key": "tcmobileapi.17uso",
					"doc_count": 18
				}, {
					"key": "sadmin.17usoft.com",
					"doc_count": 19
				}, {
					"key": "log.",
					"doc_count": 20
				}, {
					"key": "nat.ops.17usoft.com",
					"doc_count": 20
				}, {
					"key": "tcmobileapi.17usoft.c",
					"doc_count": 20
				}, {
					"key": "shorttour.lvcang.cn",
					"doc_count": 21
				}, {
					"key": "weekend.tongcheng.com",
					"doc_count": 21
				}, {
					"key": "bus.17u.com",
					"doc_count": 22
				}, {
					"key": "log",
					"doc_count": 22
				}, {
					"key": "log.17u.c",
					"doc_count": 24
				}, {
					"key": "m.1jingxi.com",
					"doc_count": 24
				}, {
					"key": "polinterface.17u.cn",
					"doc_count": 24
				}, {
					"key": "davinci.dss.17usoft.com",
					"doc_count": 25
				}, {
					"key": "log.17",
					"doc_count": 25
				}, {
					"key": "tongcheng.com",
					"doc_count": 26
				}, {
					"key": "lo",
					"doc_count": 28
				}, {
					"key": "posmng.ie.17usoft.com",
					"doc_count": 29
				}, {
					"key": "l",
					"doc_count": 31
				}, {
					"key": "log.17u",
					"doc_count": 31
				}, {
					"key": "log.17u.",
					"doc_count": 31
				}, {
					"key": "alert.dss.17usoft.com",
					"doc_count": 32
				}, {
					"key": "bus.17u.cn",
					"doc_count": 32
				}, {
					"key": "tw.ly.com",
					"doc_count": 32
				}, {
					"key": "financeapi.hongtu.17usoft.com",
					"doc_count": 34
				}, {
					"key": "train.17usoft.n",
					"doc_count": 34
				}, {
					"key": "ymy.17u.cn",
					"doc_count": 34
				}, {
					"key": "jipiao.17u.cn",
					"doc_count": 35
				}, {
					"key": "kefu.tcent.cn",
					"doc_count": 41
				}, {
					"key": "ibbdms.ie.17usoft.com",
					"doc_count": 45
				}, {
					"key": "txapi.17usoft.com",
					"doc_count": 45
				}, {
					"key": "titan.dss.17usoft.com",
					"doc_count": 46
				}, {
					"key": "api.ops.dss.17usoft.com",
					"doc_count": 47
				}, {
					"key": "down.17u.com",
					"doc_count": 48
				}, {
					"key": "log.cdb.17usoft.com",
					"doc_count": 48
				}, {
					"key": "pay.17usoft.com",
					"doc_count": 48
				}, {
					"key": "tcglfinanceapi.17usoft.com",
					"doc_count": 52
				}, {
					"key": "train.17usoft.",
					"doc_count": 54
				}, {
					"key": "file.wanchengly.com",
					"doc_count": 56
				}, {
					"key": "member.17u.cn",
					"doc_count": 56
				}, {
					"key": "ibrush.ie.17usoft.com",
					"doc_count": 57
				}, {
					"key": "salesapps.17u.cn",
					"doc_count": 57
				}, {
					"key": "tuan.17u.cn",
					"doc_count": 57
				}, {
					"key": "furt.swarm.17usoft.com",
					"doc_count": 59
				}, {
					"key": "train.17",
					"doc_count": 62
				}, {
					"key": "marketing.fly.17usoft.com",
					"doc_count": 63
				}, {
					"key": "ship.ly.com",
					"doc_count": 64
				}, {
					"key": "aibuy24h.com",
					"doc_count": 65
				}, {
					"key": "sentry.fly.17usoft.com",
					"doc_count": 66
				}, {
					"key": "yuask.tcent.cn",
					"doc_count": 68
				}, {
					"key": "ebk1.17u.cn",
					"doc_count": 70
				}, {
					"key": "eflog.tcservice.17usoft.com",
					"doc_count": 75
				}, {
					"key": "train.",
					"doc_count": 77
				}, {
					"key": "train.1",
					"doc_count": 78
				}, {
					"key": "bj.rds.tcdba.17usoft.com",
					"doc_count": 84
				}, {
					"key": "globalhotel.ly.com",
					"doc_count": 84
				}, {
					"key": "union.17u.cn",
					"doc_count": 85
				}, {
					"key": "17u.cn",
					"doc_count": 86
				}, {
					"key": "inn.17u.net",
					"doc_count": 87
				}, {
					"key": "tcglhome.tcent.cn",
					"doc_count": 89
				}, {
					"key": "ev.fly.17usoft.com",
					"doc_count": 91
				}, {
					"key": "train.17usoft",
					"doc_count": 93
				}, {
					"key": "ops.dss.17usoft.com",
					"doc_count": 94
				}, {
					"key": "osspc.ie.17usoft.com",
					"doc_count": 95
				}, {
					"key": "0qniw8ciz611nmiqs1uuv.tianwang.17usoft.com",
					"doc_count": 98
				}, {
					"key": "metrics.kafka.dss.17usoft.com",
					"doc_count": 101
				}, {
					"key": "djadmin.17u.com",
					"doc_count": 103
				}, {
					"key": "wx.aigobo.cn",
					"doc_count": 105
				}, {
					"key": "train.17u",
					"doc_count": 106
				}, {
					"key": "train.17us",
					"doc_count": 106
				}, {
					"key": "flightsharepic.fly.17usoft.com",
					"doc_count": 107
				}, {
					"key": "job.titan.dss.17usoft.com",
					"doc_count": 108
				}, {
					"key": "jp6in1zhxsrv.17u.cn",
					"doc_count": 108
				}, {
					"key": "apm.hbase.dss.17usoft.com",
					"doc_count": 112
				}, {
					"key": "glgdora.17usoft.com",
					"doc_count": 112
				}, {
					"key": "train.17usof",
					"doc_count": 115
				}, {
					"key": "monitor.kafka.dss.17usoft.com",
					"doc_count": 117
				}, {
					"key": "www.51jiesan.com",
					"doc_count": 123
				}, {
					"key": "www.usousou.com",
					"doc_count": 125
				}, {
					"key": "train.17uso",
					"doc_count": 127
				}, {
					"key": "basepay2.t.17usoft.com",
					"doc_count": 128
				}, {
					"key": "train",
					"doc_count": 128
				}, {
					"key": "springverify.fly.17usoft.com",
					"doc_count": 131
				}, {
					"key": "grafana.ops.17usoft.com",
					"doc_count": 136
				}, {
					"key": "www.tongcheng.com",
					"doc_count": 136
				}, {
					"key": "common.tianwang.17usoft.com",
					"doc_count": 137
				}, {
					"key": "tag.17u.cn",
					"doc_count": 137
				}, {
					"key": "tcops.17usoft.com",
					"doc_count": 144
				}, {
					"key": "incrementorder.train.hbase.dss.17usoft.com",
					"doc_count": 145
				}, {
					"key": "thor.fly.17usoft.com",
					"doc_count": 145
				}, {
					"key": "gs.yiqiyou.com",
					"doc_count": 157
				}, {
					"key": "tag.ly.com",
					"doc_count": 175
				}, {
					"key": "issyncisms.ie.17usoft.com",
					"doc_count": 178
				}, {
					"key": "beetle.dss.17usoft.com",
					"doc_count": 179
				}, {
					"key": "sz.escloud.dss.17usoft.com",
					"doc_count": 182
				}, {
					"key": "fms.fly.17usoft.com",
					"doc_count": 183
				}, {
					"key": "trai",
					"doc_count": 184
				}, {
					"key": "jiaotongms.17u.cn",
					"doc_count": 188
				}, {
					"key": "tr",
					"doc_count": 190
				}, {
					"key": "leonidmanager2.17usoft.com",
					"doc_count": 194
				}, {
					"key": "tuan.ly.com",
					"doc_count": 196
				}, {
					"key": "itrademng.ie.17usoft.com",
					"doc_count": 198
				}, {
					"key": "top.ly.com",
					"doc_count": 200
				}, {
					"key": "passport.17u.cn",
					"doc_count": 205
				}, {
					"key": "kefu.17u.cn",
					"doc_count": 210
				}, {
					"key": "jqebooking.17u.cn",
					"doc_count": 219
				}, {
					"key": "www.beetown.cn",
					"doc_count": 221
				}, {
					"key": "t",
					"doc_count": 226
				}]

for item in Asin:
	print (item['key'])